=== ConnectionMaster/jiradog/metrics.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "array",
  "definitions": {
    "data_provider": {
      "type": "object",
      "properties": {
        "__comment": {
          "type": "string"
        },
        "source": {
          "type": "string"
        },
        "jql": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "filter": {
          "type": "string"
        },
        "statuses": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "source": {
                "type": "string",
                "pattern": "issue|changelog"
              },
              "date": {
                "type": "string",
                "pattern": "^{({|%|#).*(}|%|#)}$"
              }
            }
          }
        }
      },
      "required": [
        "source",
        "jql",
        "method"
      ]
    }
  },
  "items": {
  "type": "object",
  "properties": {
    "metric_name": {
      "type": "string",
      "pattern": "(jiradog)(\\.)(([a-z0-9]+)([A-Z]{1}[a-z]*)*)\\.(([a-z0-9]+)([A-Za-z]*)+)"
    },
    "__comment": {
      "type": "string"
    },
    "projects": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "method": {
      "type": "string"
    },
    "issues": {
      "$ref": "#/definitions/data_provider"
    },
    "numerator": {
      "$ref": "#/definitions/data_provider"
    },
    "denominator": {
      "$ref": "#/definitions/data_provider"
    },
    "grouping": {
      "type": "object",
      "properties": {
        "by": {
          "type": "string",
          "pattern": "sprint"
        },
        "count": {
          "type": "string"
        },
        "boards": {
          "type": "object",
          "patternProperties": {
            "[A-Z]*": {
              "type": "number"
            }
          }
        }
      },
      "required": [
        "by",
        "count"
      ]
  }
},
"allOf": [
  {
    "required": [
      "metric_name",
      "projects",
      "method"
    ]
  },
  {
    "oneOf": [
      {
        "required": [
          "issues"
        ]
      },
      {
        "required": [
          "numerator",
          "denominator"
        ]
      }
    ]
  }
]
}
}

=== ConnectionMaster/jiradog/metrics.json
[
  {
    "metric_name": "jiradog.countOpenBugs",
    "__comment": "example metrics file",
    "projects": [
      "[project0]",
      "[project1]",
      "[project2]"
      ],
    "method": "direct",
    "issues": {
      "source": "jira",
      "jql": "project={{project}} AND issueType=Bug AND resolution=unresolved",
      "method": "ticket_count"
      }
  }
]

=== ConnectionMaster/jiradog/number_of_tickets_reopened.json
{
  "__comment": "SYS-1633",
  "projects": [
    "MACOSNOTE",
    "WINNOTE",
    "ION",
    "IOSNOTE",
    "DRDNOTE",
    "CE",
    "ENB"
    ],
  "method": "direct",
  "issues": {
    "source": "jira",
    "jql": "Project={{project}} AND Status WAS 'Reopened' AND Updated>endOfDay(-90d)",
    "method": "ticket_count"
    },
  "metric_name": "jiradog.numberOfBugsReopened"
}
